version: '3'
services:
  nginx:
    image: adhub424.azurecr.io/proxy:v2
    ports: 
      - 80:80
    depends_on:
      - angular
    restart: always
    networks: 
      - adhub_net

  angular:
    image: adhub424.azurecr.io/frontend:latest
    ports:
      - 4200:4200
    networks: 
      - adhub_net
      
networks: 
  adhub_net:
  
